apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloud

resources:
  - db.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  # SealedSecret 'nextcloud-secrets' (admin pass, db pass) — kubeseal
  # - sealed-secret.yaml
