apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia
  namespace: auth
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - auth.neleoz.com
      secretName: authelia-tls
  rules:
    - host: auth.neleoz.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authelia
                port:
                  number: 80
